# Generated by Django 4.0 on 2023-06-15 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='socio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.socio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='socio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.socio'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pedido'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producto'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.stockproducto'),
        ),
        migrations.AlterUniqueTogether(
            name='stockproducto',
            unique_together={('nombre', 'producto')},
        ),
    ]
