describe('Caso de prueba: Modificar parámetros de la web', () => {
    it('Correct data', () => {
      cy.viewport(1315, 961);
      cy.visit("/login-admin");
      cy.get("#username").click();
      cy.get("#username").type("admin");
      cy.get("#password").click();
      cy.get("#password").type("admin123");
      cy.get("button").click();
      cy.location("pathname").should("eq", "/gestion/buzon");
      cy.get("li:nth-of-type(3) > a").click();
      cy.get("nav > button").click();
      cy.get("#first_name").type("Test creacion producto");
      cy.get("#descripcion").type("Test de cypress");
      cy.get("#precio_general").type("20.5");
      cy.get("#precio_socio").type("15.65");
      cy.get("#imagen").click();
      cy.get("#imagen").type("https://www.cypress.com/cypress.jpg");
      cy.get("#nombre_stockNuevo").type("Test");
      cy.get("#stockNuevo").click();
      cy.get("#stockNuevo").type("8");
      cy.get("div.card-body button").click();
      cy.get("div.card-footer button").click();
      cy.location("pathname").should("eq", "/dashboard/productos");
      cy.get('div.p-1.my-container.active-cont').find('table.table-bordered').contains('Test creacion producto').parents('tr').click();
      cy.wait(2000);
      cy.get("#first_name").click();
      cy.get("#first_name").clear();
      cy.get("#first_name").type("Modificacion producto");
      cy.get("#precio_general").click();
      cy.get("#precio_general").clear();
      cy.get("#precio_general").type("5");
      cy.get("#precio_socio").click();
      cy.get("#precio_socio").clear();
      cy.get("#precio_socio").type("5");
      cy.get("button.btn-success").click();
      cy.location("pathname").should("eq", "/dashboard/productos");
      cy.get('div.p-1.my-container.active-cont').find('table.table-bordered').contains('Modificacion producto').parents('tr').click();
      cy.wait(2000);
      cy.get("button.btn-danger").click();
      cy.location("pathname").should("eq", "/dashboard/productos");
      cy.wait(2000);
      cy.get("strong").click();
      cy.get("li:nth-of-type(9) > div > ul a").click();
      cy.location("pathname").should("eq", "/login-admin");
    });
    it('Wrong data', () => {
      cy.viewport(1315, 961);
      cy.visit("/login-admin");
      cy.get("#username").click();
      cy.get("#username").type("admin");
      cy.get("#password").click();
      cy.get("#password").type("admin123");
      cy.get("button").click();
      cy.location("pathname").should("eq", "/gestion/buzon");
      cy.get("li:nth-of-type(3) > a").click();
      cy.get("nav > button").click();
      cy.get("#precio_general").type("20.5");
      cy.get("#precio_socio").type("15.65");
      cy.get("#imagen").click();
      cy.get("#imagen").type("https://www.cypress.com/cypress.jpg");
      cy.get("#nombre_stockNuevo").type("Test");
      cy.get("#stockNuevo").click();
      cy.get("#stockNuevo").type("8");
      cy.get("div.card-body button").click();
      cy.get("div.card-footer button").click();
      cy.get('.card-body > :nth-child(2) > .mb-3 > .invalid-feedback > div').contains('Debe introducir un nombre');
      cy.get(':nth-child(3) > .mb-3 > .invalid-feedback > div').contains('Debe introducir una descripción');
      cy.get("#first_name").type("Test creacion producto");
      cy.get("#descripcion").type("Test de cypress");
      cy.get("div.card-footer button").click();
      cy.location("pathname").should("eq", "/dashboard/productos");
      cy.get('div.p-1.my-container.active-cont').find('table.table-bordered').contains('Test creacion producto').parents('tr').click();
      cy.wait(2000);
      cy.get("#first_name").click();
      cy.get("#first_name").clear();
      cy.get("#precio_general").click();
      cy.get("#precio_general").clear();
      cy.get("#precio_general").type("5");
      cy.get("#precio_socio").click();
      cy.get("#precio_socio").clear();
      cy.get("#precio_socio").type("5");
      cy.get("button.btn-success").click();
      cy.get(':nth-child(2) > .mb-3 > .invalid-feedback > div').contains('Debe introducir un nombre');
      cy.get("#first_name").type("Modificacion producto");
      cy.get("button.btn-success").click();
      cy.location("pathname").should("eq", "/dashboard/productos");
      cy.get('div.p-1.my-container.active-cont').find('table.table-bordered').contains('Modificacion producto').parents('tr').click();
      cy.wait(2000);
      cy.get("button.btn-danger").click();
      cy.location("pathname").should("eq", "/dashboard/productos");
      cy.wait(2000);
      cy.get("strong").click();
      cy.get("li:nth-of-type(9) > div > ul a").click();
      cy.location("pathname").should("eq", "/login-admin");
    });
  })