# Generated by Django 4.0 on 2023-06-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ampa', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocurso',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.socio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='socios',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='users.Socio'),
        ),
        migrations.AddField(
            model_name='clase',
            name='curso_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa.cursoescolar'),
        ),
        migrations.AddField(
            model_name='cita',
            name='asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa.asunto'),
        ),
        migrations.AddField(
            model_name='cita',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.socio'),
        ),
    ]
