# Generated by Django 4.2 on 2023-05-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa', '0003_pago_producto_pedido_lineapedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='socio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='socio',
        ),
        migrations.DeleteModel(
            name='LineaPedido',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
